# Site settings
title: ChatGPT expliqué en 5 minutes
email: 
url: https://developmentalsystems.org/chatgpt_5_minutes
description: "La série vidéo « ChatGPT en 5 mn » a été réalisée par Alexandre Torres-Leguet, Clément Romac, Thomas Carta, Pierre-Yves Oudeyer, dans l'équipe Flowers du centre Inria de l'Université de Bordeaux. Elle est distribuée sous licence Creative Commons CC-BY."
keywords: ""
meta_author: Flowers Team

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E73919 #80B3FF
  secondary: 384257 #FD6E8A
  secondary-dark: 384257 #A2122F

# Footer settings
footer:
  copyright: Inria Flowers team

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/FlowersINRIA
  - title: github
    url: https://github.com/flowersteam


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      permalink: ""
      lang: "en"
  - scope:
      path: "_posts/fr"
      type: "posts"
    values:
      permalink: ""
      lang: "fr"

texts:
  nav:
    title:
      fr: "ChatGPT expliqué en 5 minutes"
      en: "ChatGPT explained in 5 minutes"
    videos:
      fr: "Episodes"
      en: "Episodes"
    about:
      fr: "A propos"
      en: "About"
  header:
    fr: "Dans cette série de <strong>vidéos pédagogiques</strong> destinée au grand public, l’équipe de recherche <a href='https://flowers.inria.fr/' target='_blank'>
         <strong>Flowers du Centre Inria de l'université de Bordeaux</strong> 
         </a>, spécialisée en Intelligence Artificielle (IA), vous propose de mieux comprendre <strong>comment fonctionnent les modèles de langage comme ChatGPT</strong>.
         <br/>Constatant que la grande majorité des ressources éducatives sur ces modèles adoptait un format long et destiné à un public relativement averti, 
         ce projet de vidéos au <strong>format court</strong> s’adresse en particulier aux <strong>élèves et enseignants de collèges et lycées</strong>, 
         et plus généralement aux <strong>non spécialistes de l'informatique ou de l'IA</strong>."
    en: "In this series of educational videos aimed at the general public, <a href='https://flowers.inria.fr/' target='_blank'>
         <strong>the Flowers research team from the Inria Center at the University of Bordeaux</strong></a> , 
         specialized in Artificial Intelligence (AI), invites you to better understand <strong>how language models like ChatGPT work</strong>. 
         <br/>
         Recognizing that the vast majority of educational resources on these models adopted a lengthy format aimed at a relatively knowledgeable audience, 
         this project of <strong>short-format</strong> videos is particularly geared towards <strong>middle and high school students, as well as educators</strong>, and more generally towards <strong>non-specialists in computer science or AI</strong>."
  videos-section:
    title:
      fr: "Episodes"
      en: "Episodes"
    cc-by-explanation:
      fr: "Ces vidéos sont libres de droits, avec une licence Creative Commons CC-BY. Cela veut dire qu'elles peuvent être utilisées librement, à la condition que leur source soit citée (voir Crédits)."
      en: "These videos are royalty-free, with a Creative Commons CC-BY license. This means that they can be used freely, provided that their source is cited (see Credits)."
  about-section:
    title:
      fr: "A propos"
      en: "About"
    text:
      fr: "L’équipe <a href='https://flowers.inria.fr/' target='_blank'><strong>Flowers du Centre Inria de l'université de Bordeaux</strong> 
          </a>, réalise des recherches scientifiques dans le domaine de <strong>l’Intelligence Artificielle développementale</strong>. 
          En particulier, elle s’intéresse à la modélisation informatique des mécanismes d’apprentissage humain, et aux rôle de la <strong>curiosité et du langage</strong> dans le développement cognitif. 
          Elle étudie aussi les propriétés des grands modèles de langage (ChatGPT, Mistral, etc), et développe des méthodes leur permettant d’être mieux ancrés dans le monde réel. 
          <br/><br/>
          L’équipe étudie également des <strong>applications de ces travaux dans le domaine des technologies éducatives, ainsi que pour aider les scientifiques</strong> (physiciens, biologistes, etc) à explorer et à mieux comprendre de nouveaux systèmes (matériaux, réactions chimiques auto-organisées, etc)."
      en: "The <a href='https://flowers.inria.fr/' target='_blank'><strong>Flowers team at the Inria Center of the University of Bordeaux</strong></a>
          conducts scientific research in the field of <strong>developmental Artificial Intelligence</strong>. 
          In particular, they are interested in the computer modeling of human learning mechanisms and the roles of <strong>curiosity and language</strong> in cognitive development. 
          They also study the properties of large language models (ChatGPT, Mistral, etc.), and develop methods to better anchor them in the real world.
          <br/><br/>
          The team also investigates <strong>applications of these works in the field of educational technologies, as well as to assist scientists</strong> (physicists, biologists, etc.) in exploring and better understanding new systems (materials, self-organized chemical reactions, etc.)."
  footer:
    socials:
      fr: "Nous retrouver"
      en: "Find us"
    credits:
      title:
        fr: "Crédits"
        en: "Credits"
      credits:
        fr: "<a href=\"https://twitter.com/AlexandreTL2\" target=\"_blank\">Torres-Leguet, A.</a>, <a href=\"https://twitter.com/ClementRomac\" target=\"_blank\">Romac, C.</a>, <a href=\"https://twitter.com/CartaThomas2\" target=\"_blank\">Carta, T.</a>, <a href=\"https://twitter.com/pyoudeyer\" target=\"_blank\">Oudeyer, P-Y.</a> (2023) ChatGPT en 5mn: une série pédagogique pour le grand public, CC-BY, https://developmentalsystems.org/chatgpt_en_5_minutes/"
        en: "<a href=\"https://twitter.com/AlexandreTL2\" target=\"_blank\">Torres-Leguet, A.</a>, <a href=\"https://twitter.com/ClementRomac\" target=\"_blank\">Romac, C.</a>, <a href=\"https://twitter.com/CartaThomas2\" target=\"_blank\">Carta, T.</a>, <a href=\"https://twitter.com/pyoudeyer\" target=\"_blank\">Oudeyer, P-Y.</a> (2023) ChatGPT in 5 minutes: an educational series for the general public, CC-BY, https://developmentalsystems.org/chatgpt_en_5_minutes/"

